### PR TITLE
Fix #10: get URL of the uploaded picture

### LINKED ISSUE #10: Access to picture URL uploaded on google Photos
Is it possible when the photo is uploaded to Google Photo that they scan a qr code with the link to the specifc photo?

I know a part of the link https://photos.google.com/share/**AxFF4t56kiJiu89m**/2021-06-11-10-14-08_pibooth.jpg

But what is the part between the stars?

### PR DESCRIPTION
**Pull request by anxuae**
To be tested.

Plugin create the `app.previous_picture_url` with the just uploaded picture

### CODE REVIEW

**Comment by sravel** [comment]
I can test this week-end maybe, I open if need, thank !

**Comment by anxuae** [comment]
Revue and test welcome ;-)

**Comment by sravel** [comment]
I did the test on my computer on a clean install and the plugin works fine, thanks for the update!!!!

**Comment by rubkec** [comment]
how to use this variable in the QR code plugin?

**Pull request merged**
